
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: odoo
    ports:
      - 5432:5432
    volumes:
      - postgres_data_odoo:/var/lib/postgresql/data
      - ./docker/init-database.sh:/docker-entrypoint-initdb.d/init-database.sh

volumes:
  postgres_data_odoo:
